CREATE TABLE IF NOT EXISTS TINDER.USER
(
    ID SERIAL,
    CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    TELEGRAM_ID VARCHAR (255),
    NAME VARCHAR (255),
    GENDER VARCHAR (255),
    PREFERENCE VARCHAR (255),
    DESCRIPTION VARCHAR (1000),
    STAGE_OF_QUESTIONNAIRE INTEGER DEFAULT 1 NOT NULL,
    PREVIOUS_USER_ID INTEGER DEFAULT 1 NOT NULL,
    NEXT_USER_ID INTEGER  DEFAULT 1 NOT NULL,
    PRIMARY KEY (TELEGRAM_ID)
);

CREATE TABLE IF NOT EXISTS TINDER.LIKED_USER
(
    ID SERIAL,
    USER_ID INTEGER NOT NULL,
    LIKED_USER_ID INTEGER NOT NULL,
    PRIMARY KEY (USER_ID, LIKED_USER_ID)
);